### ISSUE TITLE
err network electron-speech

### ISSUE THREAD

**Issue by VladCherniavsky** [noffle/electron-speech#12]
I added code example from github page to my electron application. At the end I have `err network` in console.
Any ideas ?

```var Speech = require('electron-speech')

var recog = Speech({
  lang: 'en-US',
  continuous: true
})

recog.on('text', function (text) {
  console.log(text)
});

recog.listen()

**Comment by hackergrrl** [comment]
Yes, this is (unfortunately) normal. Check out [the README](https://github.com/noffle/electron-speech#defunct) for more details.
