### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by shivang-pokar** [noffle/electron-speech#13]
It's showing this error please me out !

> 
> Uncaught Error: Uncaught, unspecified "error" event. (network)
>     at Speech.emit (events.js:166)
>     at SpeechRecognition.recognition.onerror

**Comment by hackergrrl** [comment]
Hey @sivu07, check out the [README](https://github.com/noffle/electron-speech#defunct):

> It seems that Google has shut down the Chrome Speech API for use in shell environments like Electron, which electron-speech relies on.
>
> Some other promising projects include:
>
> Sonus: node module that is optimized for low powered devices and provides customizable offline hotword detection with real-time streaming results (via Google Cloud Speech and others).
> If you are looking for a purely offline option: node-pocketsphinx
> Jasper looks promising, but is Python-based. Go forth and write a node wrapper around it!
