### ISSUE TITLE
Does it still work

### ISSUE THREAD

**Issue by Mirefire** [noffle/electron-speech#14]
Hello, friend, it has been three years, can this open source library still be used in Electron? I really need this open source library for electron now, and it is not updated anymore. Or is there any good audio open source library introduction

**Comment by hackergrrl** [comment]
No, it needs to be modified to work with the Speech API changes to
Chrome that Google made.

**Comment by Mirefire** [comment]
thank you，Google:SpeechSynthesis?

**Comment by hackergrrl** [comment]
I don't remember what it's called, but speech synthesis sounds like
text-to-voice, which is the opposite of what you want.

**Comment by emanuelnogueiras** [comment]
Anyone knows an alternative for speech to text ??

**Comment by hackergrrl** [comment]
- You can still access Google Voice via their own API.
- https://github.com/sdkcarlos/artyom.js looks maybe promising.
- [pocketsphinx](https://github.com/cmusphinx/pocketsphinx) is a purely local option that could be worth exploring.
