### ISSUE TITLE
ReferenceError: window is not defined at new Speech (E:\Projetos\Node\Electron\google-assistant\node_modules\electron-speech\index.js:13:38)

### ISSUE THREAD

**Issue by xdxddxd** [noffle/electron-speech#15]
![image](https://user-images.githubusercontent.com/38227342/110404745-2a4e7c80-805e-11eb-8fcf-52b9e0760ea1.png)

this error appears when I try to use this package in the npm runkit and in my code with electronjs !

how can I solve?

**Comment by hackergrrl** [comment]
https://github.com/noffle/electron-speech#defunct
