### ISSUE TITLE
Network error ?

### ISSUE THREAD

**Issue by Oxey405** [noffle/electron-speech#16]
Hello ! I was testing this module but when I started my app and looked in the console I got the message : "err network" and
`Uncaught Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('network')
    at Speech.emit (events.js:304)
    at SpeechRecognition.recognition.onerror `
I don't understand !

**Comment by hackergrrl** [comment]
https://github.com/noffle/electron-speech#defunct
