### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by nylki** [noffle/electron-speech#7]
In electron 1.4.8 I get the following error:

```
Uncaught Exception:
ReferenceError: window is not defined
    at new Speech (/home/tom/Programming/speechrecognition_playground/node_modules/electron-speech/index.js:13:38)
    at Speech (/home/tom/Programming/speechrecognition_playground/node_modules/electron-speech/index.js:12:43)
    at App.<anonymous> (/home/tom/Programming/speechrecognition_playground/main.js:32:14)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
```

Here is my `main.js` I used, for reference: https://gist.github.com/nylki/6ca1de80017f26b3049e032836634328

**Comment by hackergrrl** [comment]
How are you running the program? `node main.js` won't work, you need to launch with electron-spawn: `electron-spawn main.js`.

**Comment by nylki** [comment]
I am running it with `electron .`, I have a UI, therefore using `electron-spawn` is no option really. I'll close this then as unfixable, right?

**Comment by hackergrrl** [comment]
Hm. `ReferenceError: window is not defined` likely indicates that the electron-speech code is being run in the node process rather than the browser process. What does your code look like?

**Comment by nylki** [comment]
> What does your code look like?

I linked my `main.js` in my initial post, the `index.html` was just a basic html file.
I put the electron-speech code now into the html file. The error is gone. But a new one appears: 
![bildschirmfoto vom 2016-11-28 17-12-31](https://cloud.githubusercontent.com/assets/1710598/20675810/df43831a-b58d-11e6-8140-bcef1a56d7f0.png)

Here is my full (edited code): https://gist.github.com/nylki/2c5f973720354d8b3bab3ed49c171d2e

**Comment by nylki** [comment]
It might be the same thing that happens when you try to use the native Recognition API inside electron instead of hosting the website via to be accessed in a regular browser. Google apparently shut down they speech recognition service for chromium-embedded situations like electron.
[this](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-html5/JJe6KD7-bb8) and [this](http://stackoverflow.com/questions/36214413/webkitspeechrecognition-returning-network-error-in-electron) may be related.

**Comment by hackergrrl** [comment]
Alas! It was a fun ride while it lasted. This module may be defunct then. However, this module's API could easily be repurposed for a  `google-speech` module that uses the Google Speech API directly.

**Comment by nylki** [comment]
@noffle Thanks for you work anyways!
